Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.IO;
// using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc;
using MyAdmin.Application.Models;
using MyAdmin.Application.Services;

namespace MyAdmin.Mvc.Controllers
{
    // [Authorize]
    public class QueryController : Controller
    {
        private readonly IHostingEnvironment hostingEnvironment;
        private IConfigurationRoot configuration { get; set; }
        public readonly QueryManager queryManager;
        public QueryController(IHostingEnvironment hostingEnvironment, IConfigurationRoot configuration)
        {
            this.queryManager = new QueryManager();
            this.hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            QueryModel model = new QueryModel()
            {
                Temas = BuscaTemas()
            };
            return View(model);
        }

        public IActionResult SalvarArquivo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ExecutaQuery([FromBody]QueryExecutaQueryDTO dto)
        {
            var data = queryManager.ExecuteQuery(dto.Banco, dto.ConnectionString, dto.Query, dto.SalvaArquivo ?? false, dto.NomeArquivo, hostingEnvironment.WebRootPath);
            return Ok(data);
        }

        [HttpPost]
        public IActionResult GetStructureDB([FromBody]QueryStructureDBDTO dto)
        {
            var data = queryManager.GetDBStructure(dto.Banco, dto.ConnectionString);
            return Ok(data);
        }

        /* Private methods */
        private List<string> BuscaTemas()
        {
            List<string> themes = new List<string>();
            DirectoryInfo dir = new DirectoryInfo(hostingEnvironment.WebRootPath + "\\codemirror\\theme\\");

            foreach (FileInfo file in dir.GetFiles())
            {
                themes.Add(Path.GetFileNameWithoutExtension(file.Name));
            }

            return themes;
        }
    }

    public class QueryStructureDBDTO
    {
        public string Sistema { get; set; }
        public string Banco { get; set; }
        public string ConnectionString { get; set; }
    }

    public class QueryExecutaQueryDTO
    {
        public string Sistema { get; set; }
        public string Ambiente { get; set; }
        public string Banco { get; set; }
        public string Query { get; set; }
        public string ConnectionString { get; set; }
        public bool? SalvaArquivo { get; set; }
        public String NomeArquivo { get; set; }
    }
}

ViewComponents/FileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyAdmin.Application.Models;

namespace MyAdmin.ViewComponents
{
    public class FileViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var model = new FileModel();
            return View(model);
        }
    }
}

ViewComponents/SistemasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MyAdmin.Application.Models;

namespace MyAdmin.ViewComponents
{
    public class SistemasViewComponent : ViewComponent
    {
        private readonly IConfigurationRoot configuration;

        public SistemasViewComponent(IConfigurationRoot configuration)
        {
            this.configuration = configuration;
        }

        public IViewComponentResult Invoke(int numberOfItems)
        {
            var model = new SistemasModel();
            model.AllowConnStringDefinition = bool.Parse(configuration["AllowConnStringDefinition"]);
            return View(model);
        }
    }
}

Views/Query/Index.cshtml
@model MyAdmin.Application.Models.QueryModel

@section navMenu
{
    <div class="navbar-form navbar-left">
        <a class="btn btn-default pull-right btn-menu-icon-flat" ng-click="query.toggleInfoDB()">
            <span ng-class="{ 'glyphicon-chevron-right': !query.infoDBVisible, 'glyphicon-chevron-left': query.infoDBVisible }" class="glyphicon"></span>
        </a>

    </div>

    @await Component.InvokeAsync("Sistemas")

    <form class="navbar-form navbar-left" role="search">
        <button id="btnExecute" type="submit" class="btn btn-default btn-menu-icon-flat" ng-click="query.executaQuery()">Execute<span class="fa fa-database"></span></button>
    </form>

    <ul class="nav navbar-nav navbar-right">
        <li>@await Component.InvokeAsync("File")</li>
        <li>
            <div class="navbar-form navbar-right"><a class="btn btn-default pull-right" title="Configuration" href="/Configuration/Index"><span class="fa fa-gear"></span></a></div>
        </li>
    </ul>
}

<div class="container-fluid" ng-init="init()">
    <div class="row">
        <div class="col-md-2" ng-show="query.infoDBVisible">
            <label>Info DB</label>
            <div class="panel-group" id="accordion-info-bd">
                <div class="panel panel-default" ng-repeat="tabela in query.dbStructure.tabelas">
                    <div class="panel-heading info-db-header" data-toggle="collapse" data-parent="#accordion-info-bd" href="#collapse_{{$index}}">
                        <h4 class="panel-title tabela">
                            {{tabela.nome}}
                        </h4>
                    </div>
                    <div id="collapse_{{$index}}" class="panel-collapse collapse">
                        <div class="panel-body panel-info-db">
                            <ul class="dropdown-menu app-dropdown-list">
                                <li ng-repeat="coluna in tabela.colunas" class="coluna">{{coluna.nome}} <span class="info-column">({{coluna.type}}({{coluna.size}}) {{coluna.descNullable}})</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div ng-class="{ 'col-md-12': !query.infoDBVisible, 'col-md-10': query.infoDBVisible }" ng-controller="EditorController as editor">

            <label>Query</label>

            <span class="glyphicon glyphicon-floppy-disk query-icon pull-right" title="Save" ng-click="query.saveQueryFile()"></span>
            <span class="fa fa-paint-brush query-icon query-theme-icon pull-right"></span>
            <span class="fa fa-undo query-icon pull-right" title="Last Query" ng-click="query.getLastQuery()"></span>
            <popover-themes ng-show="false"></popover-themes>
            @using (Html.BeginForm("ExecutaQuery", "Query", FormMethod.Get, new { id = "form-query" }))
            {

                @Html.TextAreaFor(m => m.Query, new { @class = "form-control", rows = "6" })
                <div class="codemirror-bottom-layer">
                </div>
            }
            <div class="div-query-loading">
                <img class="text-center img-query-loading" alt="" src="/Images/animated_loader.gif" ng-show="query.executing" />
            </div>
            <div class="Resultado" ng-bind-html="query.dados">
            </div>
        </div>
    </div>

    <footer>
        <div class="panel-footer app-footer" ng-class="{ 'limited-footer' : query.limitedFooter }">
            <label>Messages</label>
            <button type="button" class="navbar-toggle" style="display: inline;" ng-click="query.toggleFooter()">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar" style="background-color: #888;"></span>
                <span class="icon-bar" style="background-color: #888;"></span>
            </button>
            <p ng-bind-html="query.resultado"></p>
        </div>
    </footer>
</div>

<script id="popover-tmpl-options" type="text/x-jquery-tmpl">
    <ul id="list-themes" class="dropdown-menu">
        <li role="presentation" ng-click="editor.themeClick('default')"><a class="theme-item" tabindex="-1" href="#">default</a></li>
        @foreach (string item in Model.Temas)
        {
            <li role="presentation" ng-click="editor.themeClick('@item')"><a class="theme-item" tabindex="-1" href="#">@item</a></li>
        }
    </ul>
</script>

@section scripts{
    <script type="text/javascript" src="/js/FileSaver.js"></script>
    <script>
        $('.codemirror-bottom-layer').mousedown(function (e) {
            e.preventDefault();

            //Salva os parametros necessários
            var y = e.pageY;
            var curHeight = $('.CodeMirror').height();

            $('html').addClass('cursor-resize');
            $('html').mousemove(function (ev) {
                //Set o tamanho do codemirror de acordo com o tamanho original e a posição do mouse.
                $('.CodeMirror').css("height", curHeight + ev.pageY - y);
            });

            $('html').mouseup(function (e) {
                e.preventDefault();

                $('html').removeClass('cursor-resize');
                $('html').unbind('mousemove');
            });
        });
    </script>
}